FROM ubuntu:latest
RUN apt update && apt install -y python3 && \
    python3-pip && \
    pip install flask 
WORKDIR /DOCKER_WORK
RUN echo "Hello Docker">Hello.dat
COPY app.py . 
CMD [ "python3","app.py" ]